/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HttpM_ReqHttp */

#ifndef _Included_HttpM_ReqHttp
#define _Included_HttpM_ReqHttp
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     HttpM_ReqHttp
 * Method:    Init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HttpM_ReqHttp_Init
  (JNIEnv *, jobject, jint);

/*
 * Class:     HttpM_ReqHttp
 * Method:    UnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HttpM_ReqHttp_UnInit
  (JNIEnv *, jobject);


/*
 * Class:     HttpM_ReqHttp
 * Method:    Open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_HttpM_ReqHttp_Open
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     HttpM_ReqHttp
 * Method:    Requset
 * Signature: (ILHttpM/ReqTask;)I
 */
JNIEXPORT jint JNICALL Java_HttpM_ReqHttp_Requset
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     HttpM_ReqHttp
 * Method:    Close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_HttpM_ReqHttp_Close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
